(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Bobby Gaza, created 2010-09-18."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "black")
      (background-mode . dark)
      (background-toolbar-color . "#000000000000")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#000000000000")
      (cursor-color . "medium turquoise")
      (foreground-color . "#c0c0c0")
      (mouse-color . "black")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#ffffffffffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((display-time-mail-face . mode-line)
      (goto-address-mail-face . message-header-to-face)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . info-xref)
      (goto-address-url-mouse-face . highlight)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (php-default-face . default)
      (rmail-highlight-face . font-lock-function-name-face)
      (semantic-which-function-use-color . t)
      (tags-tag-face . default)
      (vc-annotate-very-old-color . "#0046FF")
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "#c0c0c0" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "apple-monaco"))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (antlr-font-lock-keyword-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-literal-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-ruledef-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-ruleref-face ((t (:foreground "Gray85"))))
     (antlr-font-lock-tokendef-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (antlr-font-lock-tokenref-face ((t (:foreground "Gray85"))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (bbdb-field-value ((t (nil))))
     (bbdb-name ((t (:underline t))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (nil))))
     (blank-tab-face ((t (nil))))
     (blue ((t (:bold t :foreground "blue" :weight bold))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "yellow"))))
     (border ((t (:background "black"))))
     (border-glyph ((t (:bold t :weight bold))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "gray30" :foreground "LightSkyBlue"))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "firebrick"))))
     (change-log-conditionals ((t (:background "sienna" :foreground "khaki"))))
     (change-log-date ((t (:foreground "gold"))))
     (change-log-email ((t (:foreground "khaki" :underline t))))
     (change-log-file ((t (:foreground "Blue"))))
     (change-log-function ((t (:background "sienna" :foreground "khaki"))))
     (change-log-list ((t (:foreground "wheat"))))
     (change-log-name ((t (:foreground "Maroon"))))
     (clearcase-dired-checkedout-face ((t (:foreground "red"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "yellow"))))
     (compilation-error ((t (:bold t :foreground "red" :weight bold))))
     (compilation-info ((t (:bold t :foreground "Green1" :weight bold))))
     (compilation-line-number ((t (:foreground "violet"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "apple-monaco"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (:bold t :foreground "maroon" :weight bold))))
     (cparen-around-begin-face ((t (:foreground "maroon"))))
     (cparen-around-conditional-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (cparen-around-define-face ((t (:bold t :foreground "Blue" :weight bold))))
     (cparen-around-lambda-face ((t (:foreground "LightSeaGreen"))))
     (cparen-around-letdo-face ((t (:bold t :foreground "LightSeaGreen" :weight bold))))
     (cparen-around-quote-face ((t (:foreground "SaddleBrown"))))
     (cparen-around-set!-face ((t (:foreground "OrangeRed"))))
     (cparen-around-syntax-rules-face ((t (:foreground "Magenta"))))
     (cparen-around-vector-face ((t (:foreground "chocolate"))))
     (cparen-binding-face ((t (:foreground "ForestGreen"))))
     (cparen-binding-list-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (cparen-conditional-clause-face ((t (:foreground "RoyalBlue"))))
     (cparen-normal-paren-face ((t (:foreground "grey50"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-here-face ((t (nil))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cperl-pod-face ((t (nil))))
     (cperl-pod-head-face ((t (nil))))
     (cursor ((t (:background "medium turquoise"))))
     (custom-button ((t (:foreground "gainsboro"))))
     (custom-button-face ((t (nil))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-changed-face ((t (:bold t :background "blue" :foreground "white" :weight bold))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation ((t (:foreground "light blue"))))
     (custom-documentation-face ((t (:bold t :background "wheat" :foreground "purple4" :weight bold))))
     (custom-face-tag ((t (:underline t))))
     (custom-face-tag-face ((t (:bold t :underline t :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (custom-group-tag-1 ((t (:foreground "pale turquoise" :underline t))))
     (custom-group-tag-face ((t (:bold t :background "wheat" :foreground "blue" :underline t :weight bold))))
     (custom-group-tag-face-1 ((t (:bold t :background "wheat" :foreground "red" :underline t :weight bold))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-invalid-face ((t (:bold t :background "red" :foreground "yellow" :weight bold))))
     (custom-link ((t (:foreground "cyan1" :underline t))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-modified-face ((t (:bold t :background "blue" :foreground "white" :weight bold))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-rogue-face ((t (:bold t :background "black" :foreground "pink" :weight bold))))
     (custom-saved ((t (:underline t))))
     (custom-saved-face ((t (:bold t :underline t :weight bold))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-set-face ((t (:bold t :background "white" :foreground "blue" :weight bold))))
     (custom-state ((t (:foreground "light salmon"))))
     (custom-state-face ((t (:bold t :background "wheat" :foreground "dark green" :weight bold))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-button-face ((t (:underline t))))
     (custom-variable-tag ((t (:bold t :foreground "turquoise" :weight bold))))
     (custom-variable-tag-face ((t (:bold t :background "wheat" :foreground "blue" :underline t :weight bold))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (:foreground "cyan"))))
     (diary-face ((t (:foreground "red"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:foreground "grey50"))))
     (diff-header ((t (:foreground "lemon chiffon"))))
     (diff-hunk-header ((t (:background "grey85"))))
     (diff-index ((t (:bold t :background "grey70" :weight bold))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :background "grey70" :weight bold))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:bold t :foreground "aquamarine" :weight bold))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (:background "grey75" :foreground "gray30"))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "gray95"))))
     (dired-flagged ((t (:bold t :foreground "Red" :weight bold))))
     (dired-header ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "pale green"))))
     (dired-marked ((t (:bold t :foreground "Red" :weight bold))))
     (dired-perm-write ((t (:foreground "deeppink"))))
     (dired-symlink ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (dired-warning ((t (:bold t :foreground "Red" :weight bold))))
     (display-time-mail-balloon-enhance-face ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (display-time-mail-balloon-gnus-group-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (display-time-time-balloon-face ((t (:bold t :background "light salmon" :foreground "dark green" :weight bold))))
     (dropdown-list-face ((t (:background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "apple-bitstream vera sans mono"))))
     (dropdown-list-selection-face ((t (:background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :family "apple-bitstream vera sans mono"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class-face ((t (:foreground "Gray85"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class-face ((t (:bold t :foreground "Gray85" :weight bold))))
     (ebrowse-tree-mark-face ((t (:foreground "Gray85"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (nil))))
     (erc-error-face ((t (:bold t :weight bold))))
     (erc-fool-face ((t (:foreground "Gray85"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (nil))))
     (erc-inverse-face ((t (nil))))
     (erc-keyword-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-notice-face ((t (nil))))
     (erc-pal-face ((t (nil))))
     (erc-prompt-face ((t (nil))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (nil))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "Blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (nil))))
     (eshell-ls-product-face ((t (:foreground "OrangeRed"))))
     (eshell-ls-readonly-face ((t (:foreground "Brown"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "DarkCyan" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "wheat"))))
     (eshell-ls-todo-face ((t (:foreground "wheat"))))
     (eshell-ls-unreadable-face ((t (:foreground "Grey30"))))
     (eshell-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (extra-whitespace-face ((t (:background "pale green"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "gray85"))))
     (fl-doc-string-face ((t (nil))))
     (fl-function-name-face ((t (:foreground "green"))))
     (fl-keyword-face ((t (:foreground "LightGreen"))))
     (fl-string-face ((t (:foreground "light coral"))))
     (fl-type-face ((t (:foreground "cyan"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flymake-errline ((t (:background "LightPink"))))
     (flymake-warnline ((t (:background "LightBlue2"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (nil))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (nil))))
     (font-latex-sedate-face ((t (nil))))
     (font-latex-string-face ((t (nil))))
     (font-latex-warning-face ((t (nil))))
     (font-lock-builtin-face ((t (:foreground "#ffaa00"))))
     (font-lock-comment-delimiter-face ((t (:foreground "deeppink"))))
     (font-lock-comment-face ((t (:foreground "Red"))))
     (font-lock-constant-face ((t (:foreground "#00ff00"))))
     (font-lock-doc-face ((t (:foreground "light sky blue"))))
     (font-lock-doc-string-face ((t (:bold t :background "wheat" :foreground "purple4" :weight bold))))
     (font-lock-emphasized-face ((t (:bold t :weight bold))))
     (font-lock-exit-face ((t (nil))))
     (font-lock-function-name-face ((t (:foreground "#4186be"))))
     (font-lock-keyword-face ((t (:foreground "#00ffff"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (:italic t :bold t :slant italic :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "DarkBlue" :weight bold))))
     (font-lock-preprocessor-face ((t (:bold t :background "wheat" :foreground "orchid4" :weight bold))))
     (font-lock-reference-face ((t (:bold t :background "wheat" :foreground "red3" :weight bold))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-special-comment-face ((t (nil))))
     (font-lock-special-keyword-face ((t (nil))))
     (font-lock-string-face ((t (:foreground "#ffff00"))))
     (font-lock-type-face ((t (:foreground "Coral"))))
     (font-lock-variable-name-face ((t (:bold t :foreground "white" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "Grey15"))))
     (gdb-arrow-face ((t (:bold t :background "LightGreen" :foreground "black" :weight bold))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "Khaki"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "Coral"))))
     (gnus-cite-face-3 ((t (:foreground "#4186be"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "IndianRed"))))
     (gnus-cite-face-6 ((t (:foreground "dark violet"))))
     (gnus-cite-face-7 ((t (:foreground "SteelBlue4"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (nil))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "ForestGreen"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "#4186be" :slant italic))))
     (gnus-header-from-face ((t (:foreground "Coral"))))
     (gnus-header-name-face ((t (:foreground "white"))))
     (gnus-header-newsgroups-face ((t (:italic t :foreground "#4186be" :slant italic))))
     (gnus-header-subject-face ((t (:foreground "#4186be"))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight bold))))
     (gnus-signature-face ((t (:foreground "white"))))
     (gnus-splash ((t (nil))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "firebrick" :slant italic))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "firebrick"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:bold t :foreground "green" :weight bold))))
     (gui-button-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (gui-element ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "yellow"))))
     (highlight ((t (:background "#c0c0c0" :foreground "black"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highlight-current-line-face ((t (:background "wheat"))))
     (highline-face ((t (:background "paleturquoise"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday-face ((t (:background "pink"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (hproperty:but-face ((t (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
     (hproperty:flash-face ((t (:bold t :background "wheat" :foreground "gray80" :weight bold))))
     (hproperty:highlight-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (:foreground "DarkRed"))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "gray85" :underline t))))
     (html-helper-italic-face ((t (:italic t :slant italic))))
     (html-helper-underline-face ((t (:foreground "Black" :underline t))))
     (html-tag-face ((t (:foreground "Blue"))))
     (hyper-apropos-documentation ((t (:foreground "white"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "gray85" :weight bold))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "green"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "red"))))
     (info-header-node ((t (:bold t :weight bold))))
     (info-header-xref ((t (:bold t :foreground "sky blue" :weight bold))))
     (info-menu-5 ((t (:underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-menu-star ((t (:underline t))))
     (info-node ((t (:italic t :bold t :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (info-title-2 ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (info-title-3 ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (info-title-4 ((t (:bold t :weight bold :family "helv"))))
     (info-xref ((t (:bold t :weight bold))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:bold t :background "pale turquoise" :foreground "blue" :weight bold))))
     (isearch-secondary ((t (:foreground "red3"))))
     (ispell-face ((t (:bold t :weight bold))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-operator-face ((t (:foreground "cyan3"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (linemenu-face ((t (nil))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (list-mode-item-selected ((t (:bold t :background "gray68" :foreground "black" :weight bold))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message-face ((t (:background "grey85"))))
     (m4-face ((t (:background "gray90" :foreground "orange3"))))
     (mac-ts-block-fill-text ((t (:underline t))))
     (mac-ts-caret-position ((t (nil))))
     (mac-ts-converted-text ((t (:underline "gray20"))))
     (mac-ts-no-hilite ((t (:background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "apple-monaco"))))
     (mac-ts-outline-text ((t (:underline t))))
     (mac-ts-raw-text ((t (:underline t))))
     (mac-ts-selected-converted-text ((t (:underline t))))
     (mac-ts-selected-raw-text ((t (:underline t))))
     (mac-ts-selected-text ((t (:underline t))))
     (magenta ((t (:foreground "gray85"))))
     (magit-branch ((t (:bold t :weight bold))))
     (magit-diff-add ((t (:foreground "white"))))
     (magit-diff-del ((t (:foreground "OrangeRed"))))
     (magit-diff-file-header ((t (nil))))
     (magit-diff-hunk-header ((t (:italic t :slant italic))))
     (magit-diff-none ((t (nil))))
     (magit-header ((t (nil))))
     (magit-item-highlight ((t (:background "dim gray"))))
     (magit-item-mark ((t (:foreground "orange"))))
     (magit-log-graph ((t (:foreground "grey30"))))
     (magit-log-head-label-local ((t (:background "Grey13" :foreground "LightSkyBlue1" :box 1))))
     (magit-log-head-label-remote ((t (:background "Grey11" :foreground "DarkSeaGreen2" :box 1))))
     (magit-log-head-label-tags ((t (:background "Grey13" :foreground "khaki1" :box 1))))
     (magit-log-message ((t (nil))))
     (magit-log-sha1 ((t (:foreground "tomato"))))
     (magit-log-tag-label ((t (:background "DarkGoldenRod"))))
     (magit-section-title ((t (:bold t :weight bold))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (:bold t :weight bold))))
     (man-heading ((t (:bold t :weight bold))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:family "clean"))))
     (message-cited-text ((t (:bold t :background "wheat" :foreground "brown" :weight bold))))
     (message-cited-text-face ((t (:foreground "white"))))
     (message-header-cc ((t (:foreground "light cyan"))))
     (message-header-cc-face ((t (:foreground "#4186be"))))
     (message-header-contents ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (message-header-name ((t (:foreground "LightBlue"))))
     (message-header-name-face ((t (:foreground "white"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
     (message-header-newsgroups-face ((t (:bold t :foreground "Coral" :weight bold))))
     (message-header-other ((t (:foreground "MediumAquamarine"))))
     (message-header-other-face ((t (:foreground "steel blue"))))
     (message-header-subject ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-subject-face ((t (:bold t :foreground "#4186be" :weight bold))))
     (message-header-to ((t (:bold t :foreground "light cyan" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "#4186be" :weight bold))))
     (message-header-xheader ((t (:foreground "MediumAquamarine"))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-headers ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (message-mml ((t (:foreground "ForestGreen"))))
     (message-mml-face ((t (:bold t :weight bold))))
     (message-separator ((t (:foreground "chocolate"))))
     (message-separator-face ((t (:foreground "brown"))))
     (message-url ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mlinks-link ((t (:foreground "cyan1" :underline t))))
     (mmm-cleanup-submode-face ((t (:background "Wheat"))))
     (mmm-code-submode-face ((t (:background "LightGray"))))
     (mmm-comment-submode-face ((t (:background "SkyBlue"))))
     (mmm-declaration-submode-face ((t (:background "Aquamarine"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (mmm-init-submode-face ((t (:background "Pink"))))
     (mmm-output-submode-face ((t (:background "Plum"))))
     (mmm-special-submode-face ((t (:background "MediumSpringGreen"))))
     (mode-line ((t (:background "darkslateblue" :foreground "white"))))
     (mode-line-buffer-id ((t (:background "darkslateblue" :foreground "white"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (modeline-mousable ((t (:background "darkslateblue" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "darkslateblue" :foreground "white"))))
     (mouse ((t (:background "black"))))
     (mpg123-face-cur ((t (:background "#004080" :foreground "yellow"))))
     (mpg123-face-slider ((t (:background "yellow" :foreground "black"))))
     (mumamo-background-chunk-major ((t (nil))))
     (mumamo-background-chunk-submode ((t (nil))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (nil))))
     (my-url-face ((t (:foreground "LightBlue"))))
     (next-error ((t (:background "steelblue" :foreground "white"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (nxhtml-strval-replface ((t (:bold t :foreground "red" :weight bold))))
     (nxml-attribute-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-local-name-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-attribute-value-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-attribute-value-face ((t (:foreground "#70F170"))))
     (nxml-cdata-section-CDATA-face ((t (:foreground "#ACACFC"))))
     (nxml-cdata-section-content-face ((t (nil))))
     (nxml-cdata-section-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-char-ref-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-char-ref-number-face ((t (:foreground "#00AD00"))))
     (nxml-comment-content-face ((t (:italic t :slant italic))))
     (nxml-comment-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-delimited-data-face ((t (:foreground "#70F170"))))
     (nxml-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-element-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-element-local-name-face ((t (:foreground "#ACACFC"))))
     (nxml-element-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-entity-ref-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-entity-ref-name-face ((t (:foreground "#00AD00"))))
     (nxml-glyph-face ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash-face ((t (:foreground "#ACACFC"))))
     (nxml-heading-face ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-name-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-colon-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-prefix-face ((t (:foreground "#ACACFC"))))
     (nxml-namespace-attribute-value-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-namespace-attribute-value-face ((t (:foreground "#70F170"))))
     (nxml-namespace-attribute-xmlns-face ((t (:foreground "#ACACFC"))))
     (nxml-outline-active-indicator-face ((t (:background "black" :foreground "#00ff00" :inverse-video nil :box 1 :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "apple-monaco"))))
     (nxml-outline-ellipsis-face ((t (:bold t :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight bold :height 100 :width normal :family "apple-monaco"))))
     (nxml-outline-indicator-face ((t (:background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "apple-monaco"))))
     (nxml-processing-instruction-content-face ((t (:foreground "#70F170"))))
     (nxml-processing-instruction-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-processing-instruction-target-face ((t (:foreground "#ACACFC"))))
     (nxml-prolog-keyword-face ((t (:foreground "#ACACFC"))))
     (nxml-prolog-literal-content-face ((t (:foreground "#70F170"))))
     (nxml-prolog-literal-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-ref-face ((t (:foreground "#00AD00"))))
     (nxml-tag-delimiter-face ((t (:foreground "#00AD00"))))
     (nxml-tag-slash-face ((t (:foreground "#ACACFC"))))
     (nxml-text-face ((t (nil))))
     (nxml-where-marking ((t (:background "#00ff00" :foreground "black"))))
     (outline-1 ((t (:foreground "purple"))))
     (outline-2 ((t (:foreground "violet"))))
     (outline-3 ((t (:foreground "red"))))
     (outline-4 ((t (:foreground "magenta"))))
     (outline-5 ((t (:foreground "deeppink"))))
     (outline-6 ((t (:foreground "blue"))))
     (outline-7 ((t (:foreground "yellow"))))
     (outline-8 ((t (:foreground "cyan"))))
     (p4-diff-del-face ((t (:bold t :weight bold))))
     (paren-blink-off ((t (:foreground "gray"))))
     (paren-blink-on ((t (:foreground "purple"))))
     (paren-face ((t (nil))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "darkseagreen2"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "black"))))
     (paren-mismatch-face ((t (:bold t :weight bold))))
     (paren-no-match-face ((t (:bold t :weight bold))))
     (pointer ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (primary-selection ((t (:bold t :background "medium sea green" :weight bold))))
     (query-replace ((t (:background "palevioletred2" :foreground "brown4"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:bold t :foreground "red" :weight bold))))
     (region ((t (:background "darkslateblue" :foreground "white"))))
     (right-margin ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (rng-error-face ((t (:underline "red"))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "yellow"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (:foreground "maroon"))))
     (scroll-bar ((t (:background "grey75"))))
     (searchm-buffer ((t (:bold t :weight bold))))
     (searchm-button ((t (:bold t :weight bold))))
     (searchm-field ((t (nil))))
     (searchm-field-label ((t (:bold t :weight bold))))
     (searchm-highlight ((t (:bold t :weight bold))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-tag-highlight-face ((t (:background "#AAAA33"))))
     (semantic-tag-highlight-start-face ((t (:background "#AAAA33"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray80"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (setnu-line-number-face ((t (:italic t :background "White" :foreground "MediumPurple3" :slant italic))))
     (sgml-comment-face ((t (:foreground "dark turquoise"))))
     (sgml-doctype-face ((t (:foreground "orange"))))
     (sgml-end-tag-face ((t (:foreground "greenyellow"))))
     (sgml-entity-face ((t (:foreground "gold"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-namespace ((t (:foreground "magenta"))))
     (sgml-pi-face ((t (:foreground "lime green"))))
     (sgml-sgml-face ((t (:foreground "yellow"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-shortref-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-input-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (shell-option-face ((t (:bold t :background "wheat" :foreground "turquoise4" :weight bold))))
     (shell-output-2-face ((t (:bold t :background "wheat" :foreground "dark goldenrod" :weight bold))))
     (shell-output-3-face ((t (:bold t :background "wheat" :foreground "dark goldenrod" :weight bold))))
     (shell-output-face ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (shell-prompt-face ((t (:bold t :background "wheat" :foreground "dark orchid" :weight bold))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match ((t (:background "purple" :foreground "white"))))
     (show-paren-mismatch ((t (:background "red" :foreground "white"))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "Gray85"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (special-string-face ((t (:foreground "light green"))))
     (speedbar-button-face ((t (:bold t :foreground "green4" :weight bold))))
     (speedbar-directory-face ((t (:bold t :foreground "blue4" :weight bold))))
     (speedbar-file-face ((t (:bold t :foreground "cyan4" :weight bold))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (svn-log-partner-highlight-face ((t (:bold t :weight bold))))
     (svn-status-blame-highlight-face ((t (:background "dark slate blue" :foreground "light blue"))))
     (svn-status-blame-rev-number-face ((t (:foreground "LightGoldenrod"))))
     (svn-status-directory-face ((t (:foreground "lightskyblue1"))))
     (svn-status-filename-face ((t (:foreground "beige"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "palegreen2"))))
     (svn-status-marked-popup-face ((t (:foreground "palegreen2"))))
     (svn-status-switched-face ((t (:foreground "Aquamarine"))))
     (svn-status-symlink-face ((t (:foreground "cyan"))))
     (svn-status-update-available-face ((t (:foreground "yellow"))))
     (swbuff-current-buffer-face ((t (:bold t :weight bold))))
     (tabbar-button-face ((t (:background "gray72" :foreground "dark red" :box (:line-width 2 :color "white" :style released-button) :height 1.0 :family "helv"))))
     (tabbar-default-face ((t (:background "gray72" :foreground "gray60" :height 1.0 :family "helv"))))
     (tabbar-selected-face ((t (:background "gray72" :foreground "blue" :box (:line-width 2 :color "white" :style released-button) :height 1.0 :family "helv"))))
     (tabbar-separator-face ((t (:background "gray72" :foreground "gray60" :height 0.2 :family "helv"))))
     (tabbar-unselected-face ((t (:background "gray72" :foreground "gray60" :box (:line-width 2 :color "white" :style pressed-button) :height 1.0 :family "helv"))))
     (tabkey2-highlight-line ((t (:background "darkolivegreen"))))
     (tabkey2-highlight-message ((t (:background "darkolivegreen"))))
     (tabkey2-highlight-popup ((t (:background "darkolivegreen" :foreground "black" :box 1))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "#4186be"))))
     (term-blue-bold-face ((t (:bold t :background "snow2" :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:background "snow2" :foreground "blue" :underline t))))
     (term-bluebg ((t (:background "#4186be"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "#71bebe"))))
     (term-cyan-bold-face ((t (:bold t :background "snow2" :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:background "snow2" :foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "#71bebe"))))
     (term-default ((t (:background "gray80" :foreground "gray30" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-lucida console"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (:bold t :background "snow2" :foreground "darkslategray" :weight bold))))
     (term-default-face ((t (:background "snow2" :foreground "darkslategray"))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (:background "darkslategray" :foreground "snow2"))))
     (term-default-ul-face ((t (:background "snow2" :foreground "darkslategray" :underline t))))
     (term-green ((t (:foreground "#e5f779"))))
     (term-green-bold-face ((t (:bold t :background "snow2" :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:background "snow2" :foreground "green" :underline t))))
     (term-greenbg ((t (:background "#e5f779"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "#ef9ebe"))))
     (term-magenta-bold-face ((t (:bold t :background "snow2" :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:background "snow2" :foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "#ef9ebe"))))
     (term-red ((t (:foreground "#ef8171"))))
     (term-red-bold-face ((t (:bold t :background "snow2" :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:background "snow2" :foreground "red" :underline t))))
     (term-redbg ((t (:background "#ef8171"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "#c0c0c0"))))
     (term-white-bold-face ((t (:bold t :background "snow2" :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (:background "snow2"))))
     (term-white-ul-face ((t (:background "snow2" :foreground "white" :underline t))))
     (term-whitebg ((t (:background "#c0c0c0"))))
     (term-yellow ((t (:foreground "#fff796"))))
     (term-yellow-bold-face ((t (:bold t :background "snow2" :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:background "snow2" :foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "#fff796"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading ((t (:foreground "purple"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:bold t :background "red" :foreground "wheat" :weight bold))))
     (tool-bar ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (nil))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:bold t :weight bold))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-generic-/constant-face ((t (nil))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (nil))))
     (vhdl-font-lock-variable-face ((t (nil))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (nil))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-from-face ((t (:italic t :foreground "wheat" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "gray30"))))
     (vmpc-pre-sig-face ((t (:foreground "Aquamarine"))))
     (vmpc-sig-face ((t (:foreground "LightBlue"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:bold t :foreground "gray85" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "gray85" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (which-func ((t (:foreground "Blue1"))))
     (white ((t (:foreground "white"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:background "black" :foreground "red"))))
     (widget-documentation ((t (:background "white" :foreground "dark green"))))
     (widget-field ((t (:background "gray85" :foreground "black"))))
     (widget-inactive ((t (:background "red" :foreground "dim gray"))))
     (widget-single-line-field ((t (:background "gray85" :foreground "black"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (nil))))
     (woman-unknown-face ((t (nil))))
     (x-face ((t (:bold t :background "wheat" :foreground "black" :weight bold))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (:bold t :weight bold))))
     (x-symbol-info-face ((t (nil))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (nil))))
     (xrdb-option-name-face ((t (:foreground "gray85"))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yas/mirror-highlight-face ((t (:background "gray22"))))
     (yellow ((t (:bold t :foreground "yellow" :weight bold))))
     (zmacs-region ((t (:background "darkslateblue" :foreground "white")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))