(defun my-green-theme ()
  "Color theme by Bobby Gaza, created 2006-08-24."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "#456345")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "RoyalBlue2")
      (foreground-color . "White")
      (mouse-color . "black")
      (top-toolbar-shadow-color . "#f7defbeef7de")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     (default ((t (:stipple nil :background "#456345" :foreground "White" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 100 :width normal :family "apple-monaco"))))
     (Buffer-menu-buffer-face ((t (nil))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Info-title-1-face ((t (nil))))
     (Info-title-2-face ((t (nil))))
     (Info-title-3-face ((t (nil))))
     (Info-title-4-face ((t (nil))))
     (antlr-font-lock-keyword-face ((t (nil))))
     (antlr-font-lock-literal-face ((t (nil))))
     (antlr-font-lock-ruledef-face ((t (nil))))
     (antlr-font-lock-ruleref-face ((t (nil))))
     (antlr-font-lock-tokendef-face ((t (nil))))
     (antlr-font-lock-tokenref-face ((t (nil))))
     (bbdb-company ((t (:foreground "pale green"))))
     (bbdb-field-name ((t (:foreground "medium sea green"))))
     (bbdb-field-value ((t (:foreground "dark sea green"))))
     (bbdb-name ((t (:bold t :foreground "pale green" :weight bold))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "green" :foreground "black"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "#000000000000"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "Gray80" :foreground "black"))))
     (button ((t (:bold t :weight bold))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "LightBlue"))))
     (change-log-conditionals ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-date ((t (:foreground "LightSalmon"))))
     (change-log-email ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-file ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-function ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (change-log-list ((t (:foreground "Salmon"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (clearcase-dired-checkedout-face ((t (nil))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "medium aquamarine"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (completions-common-part ((t (:family "apple-monaco" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "White" :background "#456345" :stipple nil :height 100))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cparen-around-andor-face ((t (nil))))
     (cparen-around-begin-face ((t (nil))))
     (cparen-around-conditional-face ((t (nil))))
     (cparen-around-define-face ((t (nil))))
     (cparen-around-lambda-face ((t (nil))))
     (cparen-around-letdo-face ((t (nil))))
     (cparen-around-quote-face ((t (nil))))
     (cparen-around-set!-face ((t (nil))))
     (cparen-around-syntax-rules-face ((t (nil))))
     (cparen-around-vector-face ((t (nil))))
     (cparen-binding-face ((t (nil))))
     (cparen-binding-list-face ((t (nil))))
     (cparen-conditional-clause-face ((t (nil))))
     (cparen-normal-paren-face ((t (nil))))
     (cperl-array-face ((t (:foreground "Yellow"))))
     (cperl-hash-face ((t (:foreground "White"))))
     (cperl-here-face ((t (:foreground "green4"))))
     (cperl-invalid-face ((t (nil))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cperl-pod-face ((t (:foreground "brown4"))))
     (cperl-pod-head-face ((t (:foreground "steelblue"))))
     (cursor ((t (:background "RoyalBlue2"))))
     (custom-button ((t (:background "gainsboro" :foreground "dark cyan"))))
     (custom-button-face ((t (:background "gainsboro" :foreground "dark cyan"))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (nil))))
     (custom-button-pressed-face ((t (nil))))
     (custom-button-pressed-unraised ((t (:underline t :foreground "violet"))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue" :foreground "white"))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (nil))))
     (custom-comment-face ((t (nil))))
     (custom-comment-tag ((t (nil))))
     (custom-comment-tag-face ((t (nil))))
     (custom-documentation ((t (:background "gainsboro"))))
     (custom-documentation-face ((t (:background "gainsboro"))))
     (custom-face-tag ((t (:underline t))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-1 ((t (:foreground "pink" :underline t))))
     (custom-group-tag-face ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid ((t (:background "red" :foreground "yellow"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue" :foreground "white"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-saved-face ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:foreground "light blue" :underline t))))
     (custom-variable-tag-face ((t (:foreground "light blue" :underline t))))
     (cvs-filename ((t (:foreground "lightblue"))))
     (cvs-filename-face ((t (:foreground "lightblue"))))
     (cvs-handled ((t (:foreground "pink"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header ((t (:bold t :foreground "lightyellow" :weight bold))))
     (cvs-header-face ((t (:bold t :foreground "lightyellow" :weight bold))))
     (cvs-marked ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg ((t (:italic t :slant italic))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action ((t (:foreground "orange"))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown ((t (:foreground "red"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (nil))))
     (date ((t (:foreground "green"))))
     (diary-face ((t (:foreground "red"))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "grey70"))))
     (diff-file-header ((t (:bold t :weight bold))))
     (diff-function ((t (:foreground "grey70"))))
     (diff-header ((t (:foreground "light salmon"))))
     (diff-hunk-header ((t (:foreground "light salmon"))))
     (diff-index ((t (:bold t :weight bold))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (:bold t :weight bold))))
     (diff-removed ((t (nil))))
     (dired-face-boring ((t (:foreground "Gray65"))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-header ((t (nil))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "grey95"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name-face ((t (nil))))
     (ebrowse-member-attribute-face ((t (nil))))
     (ebrowse-member-class-face ((t (nil))))
     (ebrowse-progress-face ((t (nil))))
     (ebrowse-root-class-face ((t (nil))))
     (ebrowse-tree-mark-face ((t (nil))))
     (ecb-sources-face ((t (nil))))
     (edb-inter-field-face ((t (nil))))
     (edb-normal-summary-face ((t (nil))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (nil))))
     (emacs-wiki-bad-link-face ((t (nil))))
     (emacs-wiki-link-face ((t (nil))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-dangerous-host-face ((t (nil))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-fool-face ((t (nil))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-host-danger-face ((t (:foreground "red"))))
     (erc-input-face ((t (:foreground "light blue"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-keyword-face ((t (:bold t :foreground "orange" :weight bold))))
     (erc-nick-default-face ((t (nil))))
     (erc-nick-msg-face ((t (nil))))
     (erc-notice-face ((t (:foreground "light salmon"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :foreground "light blue" :weight bold))))
     (erc-timestamp-face ((t (nil))))
     (erc-underline-face ((t (nil))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Green" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "Pink"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "DarkGrey"))))
     (eshell-prompt-face ((t (:bold t :foreground "Pink" :weight bold))))
     (eshell-test-failed-face ((t (nil))))
     (eshell-test-ok-face ((t (nil))))
     (excerpt ((t (nil))))
     (extra-whitespace-face ((t (nil))))
     (face-1 ((t (:foreground "royal blue" :family "andale mono"))))
     (face-2 ((t (:foreground "DeepSkyBlue1" :overline nil :underline nil :slant normal :family "outline-andale mono"))))
     (face-3 ((t (:foreground "NavajoWhite3"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (nil))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (nil))))
     (fl-doc-string-face ((t (nil))))
     (fl-function-name-face ((t (nil))))
     (fl-keyword-face ((t (nil))))
     (fl-string-face ((t (nil))))
     (fl-type-face ((t (nil))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flyspell-duplicate-face ((t (nil))))
     (flyspell-incorrect-face ((t (nil))))
     (font-latex-bold-face ((t (:bold t :foreground "DarkOliveGreen" :weight bold))))
     (font-latex-italic-face ((t (:italic t :foreground "DarkOliveGreen" :slant italic))))
     (font-latex-math-face ((t (:foreground "burlywood"))))
     (font-latex-sedate-face ((t (:foreground "LightGray"))))
     (font-latex-string-face ((t (:foreground "RosyBrown"))))
     (font-latex-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (font-lock-builtin-face ((t (:foreground "cadetblue2"))))
     (font-lock-comment-delimiter-face ((t (:foreground "gray80"))))
     (font-lock-comment-face ((t (:foreground "gray80"))))
     (font-lock-constant-face ((t (:foreground "steelblue1"))))
     (font-lock-doc-face ((t (:foreground "light coral"))))
     (font-lock-doc-string-face ((t (:foreground "light coral"))))
     (font-lock-emphasized-face ((t (:bold t :background "lightyellow2" :weight bold))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:foreground "aquamarine"))))
     (font-lock-keyword-face ((t (:foreground "cyan"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "steelblue1"))))
     (font-lock-reference-face ((t (:foreground "cadetblue2"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-special-comment-face ((t (:foreground "blue4"))))
     (font-lock-special-keyword-face ((t (:foreground "red4"))))
     (font-lock-string-face ((t (:foreground "tan"))))
     (font-lock-type-face ((t (:foreground "wheat"))))
     (font-lock-variable-name-face ((t (:foreground "cyan3"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (nil))))
     (gdb-arrow-face ((t (:bold t :background "LightGreen" :foreground "black" :weight bold))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:foreground "light blue"))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "light cyan"))))
     (gnus-cite-face-3 ((t (:foreground "light yellow"))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "DeepPink3"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "DeepPink3" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "HotPink3"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "HotPink3" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "magenta4"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "magenta4" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "DeepPink4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "DeepPink4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "ForestGreen"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "CadetBlue4"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "CadetBlue4" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkGreen"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "lime green" :slant italic))))
     (gnus-header-from-face ((t (:foreground "spring green"))))
     (gnus-header-name-face ((t (:foreground "pink"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "SeaGreen3" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "yellow" :weight bold))))
     (gnus-picon-face ((t (nil))))
     (gnus-picon-xbm-face ((t (nil))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-server-agent-face ((t (nil))))
     (gnus-server-closed-face ((t (nil))))
     (gnus-server-denied-face ((t (nil))))
     (gnus-server-offline-face ((t (nil))))
     (gnus-server-opened-face ((t (nil))))
     (gnus-signature-face ((t (:italic t :slant italic))))
     (gnus-splash ((t (nil))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "RoyalBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "DarkGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "firebrick" :weight bold))))
     (gnus-summary-high-undownloaded-face ((t (nil))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "RoyalBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "DarkGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "firebrick" :slant italic))))
     (gnus-summary-low-undownloaded-face ((t (nil))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "RoyalBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "DarkGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "firebrick"))))
     (gnus-summary-normal-undownloaded-face ((t (nil))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "Gray80" :foreground "black"))))
     (header-line ((t (:background "#030" :foreground "#AA7"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (nil))))
     (hi-black-hb ((t (nil))))
     (hi-blue ((t (nil))))
     (hi-blue-b ((t (nil))))
     (hi-green ((t (nil))))
     (hi-green-b ((t (nil))))
     (hi-pink ((t (nil))))
     (hi-red-b ((t (nil))))
     (hi-yellow ((t (nil))))
     (highlight ((t (:background "darkseagreen2"))))
     (highlight-changes-delete-face ((t (nil))))
     (highlight-changes-face ((t (nil))))
     (highlight-current-line-face ((t (:background "wheat"))))
     (highline-face ((t (:background "Grey95"))))
     (holiday-face ((t (:background "pink"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (hproperty:but-face ((t (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
     (hproperty:flash-face ((t (:bold t :background "wheat" :foreground "gray80" :weight bold))))
     (hproperty:highlight-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (nil))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (nil))))
     (html-helper-italic-face ((t (nil))))
     (html-helper-underline-face ((t (nil))))
     (html-tag-face ((t (nil))))
     (hyper-apropos-documentation ((t (:foreground "LightSalmon"))))
     (hyper-apropos-heading ((t (nil))))
     (hyper-apropos-hyperlink ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (hyper-apropos-major-heading ((t (nil))))
     (hyper-apropos-section-heading ((t (nil))))
     (hyper-apropos-warning ((t (nil))))
     (ibuffer-deletion-face ((t (nil))))
     (ibuffer-marked-face ((t (:foreground "red"))))
     (idlwave-help-link-face ((t (nil))))
     (idlwave-shell-bp-face ((t (nil))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-indicator-face ((t (nil))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir-face ((t (:foreground "MediumSlateBlue"))))
     (info-header-node ((t (nil))))
     (info-header-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (info-menu-5 ((t (:underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (nil))))
     (info-node ((t (:bold t :foreground "DodgerBlue1" :underline t :weight bold))))
     (info-xref ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (isearch ((t (:background "paleturquoise"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (ispell-face ((t (:bold t :background "#3454b4" :foreground "yellow" :weight bold))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (nil))))
     (jde-bug-breakpoint-marker ((t (nil))))
     (jde-db-active-breakpoint-face ((t (nil))))
     (jde-db-requested-breakpoint-face ((t (nil))))
     (jde-db-spec-breakpoint-face ((t (nil))))
     (jde-java-font-lock-api-face ((t (nil))))
     (jde-java-font-lock-bold-face ((t (nil))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (nil))))
     (jde-java-font-lock-doc-tag-face ((t (nil))))
     (jde-java-font-lock-italic-face ((t (nil))))
     (jde-java-font-lock-link-face ((t (nil))))
     (jde-java-font-lock-modifier-face ((t (nil))))
     (jde-java-font-lock-number-face ((t (nil))))
     (jde-java-font-lock-operator-face ((t (nil))))
     (jde-java-font-lock-package-face ((t (nil))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (nil))))
     (lazy-highlight ((t (:foreground "red"))))
     (lazy-highlight-face ((t (:foreground "yellow"))))
     (left-margin ((t (nil))))
     (linemenu-face ((t (nil))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (log-view-file-face ((t (nil))))
     (log-view-message-face ((t (:foreground "light salmon"))))
     (m4-face ((t (:background "gray90" :foreground "orange3"))))
     (mac-input-method-face ((t (:underline t))))
     (mac-input-method-selection-face ((t (:background "light sky blue" :foreground "black" :underline t))))
     (magenta ((t (nil))))
     (makefile-space-face ((t (:background "hotpink"))))
     (man-bold ((t (nil))))
     (man-heading ((t (nil))))
     (man-italic ((t (nil))))
     (man-xref ((t (nil))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (:background "#304020" :foreground "navajo white"))))
     (message-cited-text ((t (:foreground "slategrey"))))
     (message-cited-text-face ((t (:foreground "red"))))
     (message-header-cc-face ((t (:bold t :foreground "green4" :weight bold))))
     (message-header-contents ((t (:italic t :slant italic))))
     (message-header-name-face ((t (:foreground "DarkGreen"))))
     (message-header-newsgroups-face ((t (:bold t :foreground "yellow" :weight bold))))
     (message-header-other-face ((t (:foreground "#b00000"))))
     (message-header-subject-face ((t (:foreground "green3"))))
     (message-header-to-face ((t (:bold t :foreground "green2" :weight bold))))
     (message-header-xheader-face ((t (:foreground "blue"))))
     (message-headers ((t (:bold t :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :weight bold))))
     (message-mml-face ((t (:foreground "ForestGreen"))))
     (message-separator-face ((t (:foreground "blue3"))))
     (message-url ((t (:bold t :weight bold))))
     (minibuffer-prompt ((t (:foreground "pale green"))))
     (mmm-cleanup-submode-face ((t (:background "Wheat"))))
     (mmm-code-submode-face ((t (:background "LightGray"))))
     (mmm-comment-submode-face ((t (:background "SkyBlue"))))
     (mmm-declaration-submode-face ((t (:background "Aquamarine"))))
     (mmm-default-submode-face ((t (:background "gray85"))))
     (mmm-face ((t (nil))))
     (mmm-init-submode-face ((t (:background "Pink"))))
     (mmm-output-submode-face ((t (:background "Plum"))))
     (mmm-special-submode-face ((t (:background "MediumSpringGreen"))))
     (mode-line ((t (:background "Gray80" :foreground "black"))))
     (mode-line-buffer-id ((t (:background "Gray80" :foreground "blue4"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "dark olive green" :foreground "khaki" :box (:line-width 1 :style released-button)))))
     (modeline-mousable ((t (:background "Gray80" :foreground "firebrick"))))
     (modeline-mousable-minor-mode ((t (:background "Gray80" :foreground "green4"))))
     (mouse ((t (:background "black"))))
     (mpg123-face-cur ((t (nil))))
     (mpg123-face-slider ((t (nil))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (next-error ((t (:background "gray65"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (overlay-empty-face ((t (nil))))
     (p4-diff-del-face ((t (:bold t :foreground "salmon" :weight bold))))
     (paren-blink-off ((t (:foreground "darkblue"))))
     (paren-blink-on ((t (:foreground "purple"))))
     (paren-face ((t (:background "lightgoldenrod"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "yellow" :foreground "darkblue"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "yellow"))))
     (paren-mismatch-face ((t (:background "DeepPink"))))
     (paren-no-match-face ((t (:background "yellow"))))
     (pointer ((t (:foreground "White"))))
     (primary-selection ((t (:background "gray65"))))
     (query-replace ((t (:background "paleturquoise"))))
     (reb-match-0 ((t (nil))))
     (reb-match-1 ((t (nil))))
     (reb-match-2 ((t (nil))))
     (reb-match-3 ((t (nil))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "gray65"))))
     (right-margin ((t (nil))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "yellow"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (:foreground "maroon"))))
     (ruler-mode-column-number-face ((t (:background "grey76" :foreground "black" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-current-column-face ((t (:bold t :background "grey76" :foreground "yellow" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :family "outline-andale mono"))))
     (ruler-mode-default-face ((t (:background "grey76" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-fill-column-face ((t (:background "grey76" :foreground "red" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-margins-face ((t (:background "grey64" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (ruler-mode-tab-stop-face ((t (:background "grey76" :foreground "steelblue" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :family "outline-andale mono"))))
     (scroll-bar ((t (:background "grey75"))))
     (searchm-buffer ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (searchm-button ((t (:bold t :background "CadetBlue" :foreground "white" :weight bold))))
     (searchm-field ((t (:background "grey89"))))
     (searchm-field-label ((t (:bold t :weight bold))))
     (searchm-highlight ((t (:bold t :background "darkseagreen2" :foreground "black" :weight bold))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (semantic-dirty-token-face ((t (:background "grey22"))))
     (semantic-intangible-face ((t (nil))))
     (semantic-read-only-face ((t (nil))))
     (semantic-unmatched-syntax-face ((t (nil))))
     (senator-intangible-face ((t (nil))))
     (senator-momentary-highlight-face ((t (nil))))
     (senator-read-only-face ((t (nil))))
     (setnu-line-number-face ((t (:italic t :background "White" :foreground "MediumPurple3" :slant italic))))
     (sgml-comment-face ((t (:foreground "dark green"))))
     (sgml-doctype-face ((t (:foreground "maroon"))))
     (sgml-end-tag-face ((t (:foreground "blue2"))))
     (sgml-entity-face ((t (:foreground "red2"))))
     (sgml-ignored-face ((t (:background "gray90" :foreground "maroon"))))
     (sgml-ms-end-face ((t (:foreground "maroon"))))
     (sgml-ms-start-face ((t (:foreground "maroon"))))
     (sgml-namespace ((t (:foreground "cadetblue2"))))
     (sgml-pi-face ((t (:foreground "maroon"))))
     (sgml-sgml-face ((t (:foreground "maroon"))))
     (sgml-short-ref-face ((t (:foreground "goldenrod"))))
     (sgml-shortref-face ((t (nil))))
     (sgml-start-tag-face ((t (:foreground "blue2"))))
     (sh-heredoc-face ((t (nil))))
     (shadow ((t (:foreground "grey70"))))
     (shell-input-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (shell-option-face ((t (:background "darkblue" :foreground "cyan2"))))
     (shell-output-2-face ((t (:background "darkblue" :foreground "darkseagreen"))))
     (shell-output-3-face ((t (:background "darkblue" :foreground "lightgrey"))))
     (shell-output-face ((t (:background "darkblue" :foreground "white"))))
     (shell-prompt-face ((t (:background "darkblue" :foreground "red"))))
     (show-block-face1 ((t (nil))))
     (show-block-face2 ((t (nil))))
     (show-block-face3 ((t (nil))))
     (show-block-face4 ((t (nil))))
     (show-block-face5 ((t (nil))))
     (show-block-face6 ((t (nil))))
     (show-block-face7 ((t (nil))))
     (show-block-face8 ((t (nil))))
     (show-block-face9 ((t (nil))))
     (show-paren-match ((t (:background "SlateGray1"))))
     (show-paren-match-face ((t (:background "SlateGray1"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (show-tabs-space-face ((t (nil))))
     (show-tabs-tab-face ((t (nil))))
     (smerge-base-face ((t (nil))))
     (smerge-markers-face ((t (nil))))
     (smerge-mine-face ((t (nil))))
     (smerge-other-face ((t (nil))))
     (special-string-face ((t (:foreground "light green"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "dark turquoise" :foreground "white"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (nil))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (strokes-char-face ((t (nil))))
     (svn-status-directory-face ((t (:foreground "lightskyblue1"))))
     (svn-status-filename-face ((t (:foreground "beige"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "palegreen2"))))
     (svn-status-marked-popup-face ((t (:foreground "palegreen2"))))
     (svn-status-switched-face ((t (:foreground "Aquamarine"))))
     (svn-status-symlink-face ((t (:foreground "cyan"))))
     (svn-status-update-available-face ((t (:foreground "yellow"))))
     (swbuff-current-buffer-face ((t (nil))))
     (tabbar-button-face ((t (nil))))
     (tabbar-default-face ((t (nil))))
     (tabbar-selected-face ((t (nil))))
     (tabbar-separator-face ((t (nil))))
     (tabbar-unselected-face ((t (nil))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "blue"))))
     (term-blue-bold-face ((t (nil))))
     (term-blue-face ((t (nil))))
     (term-blue-inv-face ((t (nil))))
     (term-blue-ul-face ((t (nil))))
     (term-bluebg ((t (:background "blue"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "cyan"))))
     (term-cyan-bold-face ((t (nil))))
     (term-cyan-face ((t (nil))))
     (term-cyan-inv-face ((t (nil))))
     (term-cyan-ul-face ((t (nil))))
     (term-cyanbg ((t (:background "cyan"))))
     (term-default ((t (nil))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (nil))))
     (term-default-face ((t (nil))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (nil))))
     (term-default-ul-face ((t (nil))))
     (term-green ((t (:foreground "green"))))
     (term-green-bold-face ((t (nil))))
     (term-green-face ((t (nil))))
     (term-green-inv-face ((t (nil))))
     (term-green-ul-face ((t (nil))))
     (term-greenbg ((t (:background "green"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "magenta"))))
     (term-magenta-bold-face ((t (nil))))
     (term-magenta-face ((t (nil))))
     (term-magenta-inv-face ((t (nil))))
     (term-magenta-ul-face ((t (nil))))
     (term-magentabg ((t (:background "magenta"))))
     (term-red ((t (:foreground "red"))))
     (term-red-bold-face ((t (nil))))
     (term-red-face ((t (nil))))
     (term-red-inv-face ((t (nil))))
     (term-red-ul-face ((t (nil))))
     (term-redbg ((t (:background "red"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "white"))))
     (term-white-bold-face ((t (nil))))
     (term-white-face ((t (nil))))
     (term-white-inv-face ((t (nil))))
     (term-white-ul-face ((t (nil))))
     (term-whitebg ((t (:background "white"))))
     (term-yellow ((t (:foreground "yellow"))))
     (term-yellow-bold-face ((t (nil))))
     (term-yellow-face ((t (nil))))
     (term-yellow-inv-face ((t (nil))))
     (term-yellow-ul-face ((t (nil))))
     (term-yellowbg ((t (:background "yellow"))))
     (tex-math-face ((t (nil))))
     (texinfo-heading-face ((t (nil))))
     (text-cursor ((t (:background "Pink" :foreground "Black"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (:background "lemon chiffon" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (nil))))
     (vcursor ((t (nil))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "Gray80" :foreground "black"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "SaddleBrown"))))
     (vhdl-font-lock-function-face ((t (:foreground "DarkCyan"))))
     (vhdl-font-lock-generic-/constant-face ((t (:foreground "Gold3"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (:foreground "ForestGreen"))))
     (vhdl-font-lock-variable-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (:foreground "Orchid4"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-xface ((t (nil))))
     (vmpc-pre-sig-face ((t (nil))))
     (vmpc-sig-face ((t (nil))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (white ((t (nil))))
     (widget ((t (:background "Gray80" :foreground "black"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition-face ((t (nil))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (x-face ((t (:background "white" :foreground "black"))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (:bold t :foreground "green4" :underline t :weight bold))))
     (x-symbol-info-face ((t (:foreground "green4"))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (:background "pink"))))
     (xrdb-option-name-face ((t (nil))))
     (xref-keyword-face ((t (nil))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (nil))))
     (xref-list-symbol-face ((t (nil))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "gray65")))))))